// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/access-denied" | "/admin/dashboard" | "/admin/reports" | "/audit-logs" | "/bank/audit-logs" | "/bank/dashboard" | "/bank/fund-accounts" | "/bank/profile" | "/bank/reconciliation" | "/bank/reconciliation/[id]" | "/bank/reports" | "/bank/settlements" | "/bank/transactions" | "/contact" | "/dashboard" | "/forgot-password" | "/help" | "/insurance/claims" | "/insurance/dashboard" | "/insurance/plans" | "/login" | "/members" | "/members/[id]" | "/membership" | "/notifications" | "/onboarding/mobile-money" | "/privacy-policy" | "/profile" | "/qr" | "/register" | "/reports" | "/reset-password" | "/savings" | "/services" | "/settings" | "/super-admin/administrators" | "/super-admin/dashboard" | "/super-admin/roles" | "/super-admin/saving-rules" | "/telecom" | "/telecom/airtime" | "/telecom/audit-logs" | "/telecom/bundles" | "/telecom/contribution-rules" | "/telecom/contributions" | "/telecom/dashboard" | "/telecom/members" | "/telecom/operator" | "/telecom/outgoing-diversions" | "/telecom/payments" | "/telecom/reconciliation" | "/telecom/reconciliation/[id]" | "/telecom/reports" | "/telecom/resource-conversions" | "/terms" | "/verifications" | "/wallet" | "/wallet/deposit" | "/wallet/transactions" | "/wallet/transfer" | "/wallet/withdraw"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/access-denied": {}
  "/admin/dashboard": {}
  "/admin/reports": {}
  "/audit-logs": {}
  "/bank/audit-logs": {}
  "/bank/dashboard": {}
  "/bank/fund-accounts": {}
  "/bank/profile": {}
  "/bank/reconciliation": {}
  "/bank/reconciliation/[id]": { "id": string; }
  "/bank/reports": {}
  "/bank/settlements": {}
  "/bank/transactions": {}
  "/contact": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/help": {}
  "/insurance/claims": {}
  "/insurance/dashboard": {}
  "/insurance/plans": {}
  "/login": {}
  "/members": {}
  "/members/[id]": { "id": string; }
  "/membership": {}
  "/notifications": {}
  "/onboarding/mobile-money": {}
  "/privacy-policy": {}
  "/profile": {}
  "/qr": {}
  "/register": {}
  "/reports": {}
  "/reset-password": {}
  "/savings": {}
  "/services": {}
  "/settings": {}
  "/super-admin/administrators": {}
  "/super-admin/dashboard": {}
  "/super-admin/roles": {}
  "/super-admin/saving-rules": {}
  "/telecom": {}
  "/telecom/airtime": {}
  "/telecom/audit-logs": {}
  "/telecom/bundles": {}
  "/telecom/contribution-rules": {}
  "/telecom/contributions": {}
  "/telecom/dashboard": {}
  "/telecom/members": {}
  "/telecom/operator": {}
  "/telecom/outgoing-diversions": {}
  "/telecom/payments": {}
  "/telecom/reconciliation": {}
  "/telecom/reconciliation/[id]": { "id": string; }
  "/telecom/reports": {}
  "/telecom/resource-conversions": {}
  "/terms": {}
  "/verifications": {}
  "/wallet": {}
  "/wallet/deposit": {}
  "/wallet/transactions": {}
  "/wallet/transfer": {}
  "/wallet/withdraw": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
