// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/(admin)/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(admin)/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/fund-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/fund-accounts">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/fund-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/profile">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/reconciliation/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/reconciliation/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/reconciliation/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/reconciliation">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/reports">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/settlements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/settlements">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/settlements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/bank/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank/transactions">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/bank/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(insurance)/insurance/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(insurance)/insurance/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(member)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/insurance/claims/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance/claims">> = Specific
  const handler = {} as typeof import("../../../app/(member)/insurance/claims/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/insurance/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance/plans">> = Specific
  const handler = {} as typeof import("../../../app/(member)/insurance/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/membership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/membership">> = Specific
  const handler = {} as typeof import("../../../app/(member)/membership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../app/(member)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/onboarding/mobile-money/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/mobile-money">> = Specific
  const handler = {} as typeof import("../../../app/(member)/onboarding/mobile-money/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/(member)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qr">> = Specific
  const handler = {} as typeof import("../../../app/(member)/qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/(member)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/savings">> = Specific
  const handler = {} as typeof import("../../../app/(member)/savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(member)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/telecom/airtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/airtime">> = Specific
  const handler = {} as typeof import("../../../app/(member)/telecom/airtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/telecom/bundles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/bundles">> = Specific
  const handler = {} as typeof import("../../../app/(member)/telecom/bundles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/telecom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom">> = Specific
  const handler = {} as typeof import("../../../app/(member)/telecom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/telecom/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/payments">> = Specific
  const handler = {} as typeof import("../../../app/(member)/telecom/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/verifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verifications">> = Specific
  const handler = {} as typeof import("../../../app/(member)/verifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/wallet/deposit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/deposit">> = Specific
  const handler = {} as typeof import("../../../app/(member)/wallet/deposit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet">> = Specific
  const handler = {} as typeof import("../../../app/(member)/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/wallet/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../../app/(member)/wallet/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/wallet/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/transfer">> = Specific
  const handler = {} as typeof import("../../../app/(member)/wallet/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/wallet/withdraw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wallet/withdraw">> = Specific
  const handler = {} as typeof import("../../../app/(member)/wallet/withdraw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../../app/(public)/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../app/(public)/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/(public)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(super-admin)/super-admin/administrators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/administrators">> = Specific
  const handler = {} as typeof import("../../../app/(super-admin)/super-admin/administrators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(super-admin)/super-admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(super-admin)/super-admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(super-admin)/super-admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/roles">> = Specific
  const handler = {} as typeof import("../../../app/(super-admin)/super-admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(super-admin)/super-admin/saving-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/saving-rules">> = Specific
  const handler = {} as typeof import("../../../app/(super-admin)/super-admin/saving-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/contribution-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/contribution-rules">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/contribution-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/contributions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/contributions">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/contributions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/members">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/operator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/operator">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/operator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/outgoing-diversions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/outgoing-diversions">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/outgoing-diversions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/reconciliation/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/reconciliation/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/reconciliation/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/reconciliation">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/reports">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/telecom/resource-conversions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecom/resource-conversions">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/telecom/resource-conversions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/access-denied/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access-denied">> = Specific
  const handler = {} as typeof import("../../../app/access-denied/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(bank)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(bank)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(insurance)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(insurance)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(member)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(super-admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(super-admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(telecom)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(telecom)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
